config/routes.rb
Rails.application.routes.draw do
  resources :job_scores
  devise_for :users

  resources :stat

   root 'stat#index'
   
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

end

app/models/job_score.rb
class JobScore < ActiveRecord::Base
end

app/models/stat.rb
class Stat < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/job_scores_controller.rb
class JobScoresController < ApplicationController
  before_action :set_job_score, only: [:show, :destroy]

  # GET /job_scores
  # GET /job_scores.json
  def index
    @job_scores = JobScore.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /job_scores/1
  # GET /job_scores/1.json
  def show
  end


  # DELETE /job_scores/1
  # DELETE /job_scores/1.json
  def destroy
    @job_score.destroy
    respond_to do |format|
      format.html { redirect_to job_scores_url, notice: 'Job score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_score
      @job_score = JobScore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_score_params
      params.require(:job_score).permit(:job, :start_time, :end_time, :status)
    end
end

app/controllers/stat_controller.rb
class StatController < ApplicationController

  def index
    #@stats = Stat.all

    per_page = params[:per_page] ? params[:per_page]:10

    @stats_all_time = Stat.paginate(:page => params[:page], :per_page => per_page).order("msg_count DESC")

    #@stats_all_time = Stat.order("msg_count DESC").first(10)

  end
  
  def show
    if(params[:id] == 'all')


      @stat = Stat.all
      
      respond_to do |format|
        format.html { redirect_to action: :index }
        format.xml {render :xml => @stat}
        format.json  {render :json => @stat.as_json}
      end
    else
      redirect_to action: :index
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/job_scores_helper.rb
module JobScoresHelper
  
  #Update statistics for delayed job, after execution is complete
  #Update status and completion time of the job
  def self.update_job_status(job_id, status)
    js = JobScore.where(:job_id => job_id).first
    js.status = status
    js.end_time = Time.now
    js.save!
  end
  
end

app/helpers/stat_helper.rb
module StatHelper
  
  #retrieves user from Slack
  #returns JSON that caontains all slack users 
  def self.fetch_users_from_slack
    uriUsers = URI(Rails.configuration.x.slack_users_uri)
    params = { :token => Rails.configuration.x.slack_key}
    uriUsers.query = URI.encode_www_form(params)
    Net::HTTP.start(uriUsers.host, uriUsers.port, :use_ssl => uriUsers.scheme == 'https', :verify_mode => OpenSSL::SSL::VERIFY_NONE) do |httpUsers|
      request = Net::HTTP::Get.new uriUsers

      response = httpUsers.request request
      data = JSON.parse(response.body)['members']
      return data
    end
  end
  
  #iterate through JSON with users and stores them into database (Stat table)
  def self.insert_users(users)
    users.each do |member|
      if !(Stat.where(:name => member['name']).exists?)
        Stat.create(:name=> member['name'], :full_name => member['profile']['real_name'])
      end
    end
  end
  
  #For each record in the Stat table retrieves messages from Slack (using username) 
  #After Slack response, number of messages is updated for that Stat record
  def self.update_users_messages
    Stat.all.each do |member|
      messages = fetch_messages_for_user(member.name)
      update_messages(member.name, messages)
    end
  end
  
  #Retrieves messages for specific Slack user using the Slack API
  def self.fetch_messages_for_user(user)
    uriMessages = URI(Rails.configuration.x.slack_search_all_uri)
    params = { :token => Rails.configuration.x.slack_key, :query => 'from:' + user}
    uriMessages.query = URI.encode_www_form(params)
    Net::HTTP.start(uriMessages.host, uriMessages.port, :use_ssl => uriMessages.scheme == 'https', :verify_mode => OpenSSL::SSL::VERIFY_NONE) do |httpMsg|
      request = Net::HTTP::Get.new uriMessages

      response = httpMsg.request request
      dataUser = JSON.parse(response.body)
      return dataUser['messages']["total"]
    end
  end
  
  #Updates specific Stat record with new number of messages 
  def self.update_messages(name, count)
    #Delayed::Worker.logger.info(name)
    #Delayed::Worker.logger.info(count)
    Stat.where(:name => name).update_all(:msg_count => count)
  end
  
  
end

app/views/job_scores/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Listing Job Scores</h3>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Job</th>
      <th>Start Time</th>
      <th>Duration (sec)</th>
      <th>Status</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @job_scores.each do |job_score| %>
      <tr>
        <td><%= job_score.name %></td>
        <td><%= job_score.start_time %></td>
        <td> <% if job_score.end_time.present? %>
        		<%= job_score.end_time - job_score.start_time %>
        	<% else %>
				<%= Time.now - job_score.start_time %>
			<% end %>	        	
        </td>
        <td> <% if job_score.end_time.present? %>
        		<%= job_score.status %>
        	<% else %>
				In Progress
			<% end %>	        	
        </td>
        <td><%= link_to 'Show', job_score %></td>
        <td><%= link_to 'Destroy', job_score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <tr>
	   <td colspan="6"><%= will_paginate @job_scores %></td>
	</tr>
  </tbody>
</table>

<br>

app/views/job_scores/show.html.erb
<div class="row">
<h3>Slack Jobs Statistics</h3>

<p id="notice"><%= notice %></p>


	<table class="table table-striped table-bordered">
		<tr>
			<td><strong>Job:</strong></td>
			<td><%= @job_score.name %></td>
		</tr>
		<tr>
			<td><strong>Start time:</strong></td>
			<td><%= @job_score.start_time %></td>
		</tr>
		<tr>
			<td><strong>End time:</strong></td>
			<td><%= @job_score.end_time %></td>
		</tr>
		<tr>
			<td><strong>Duration:</strong></td>
			<td>
				<% if @job_score.end_time.present? %>
					<%= @job_score.end_time - @job_score.start_time %>
			  <% else %>
					<%= Time.now - @job_score.start_time %>
			  <% end %>	sec
			</td>
		</tr>
		<tr>
			<td><strong>Status:</strong></td>
				<td>
					<% if @job_score.end_time.present? %>
						<%= @job_score.status %>
				  <% else %>
						In Progress
					<% end %>
				</td>
		</tr>
		<tr>
			<td colspan="2"><%= link_to 'Back', job_scores_path %></td>
		</tr>
	</table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SlackStats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">

<p class="navbar-text pull-right row">
  <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
</p>

<div class="clear"></div>

<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/stat/index.html.erb
<div class="row">
<h3>Top Slack Users</h3>


  <%= will_paginate @stats_all_time %>

<table class="table table-striped table-bordered">
  <tr>
    <th>Full Name</th>
    <th>User</th>
    <th>Message Count</th>
  </tr>
  <% @stats_all_time.each do |stat| %>
      <tr>
      	<td><%= stat.full_name %></td>
        <td><%= stat.name %></td>
        <td><%= stat.msg_count %></td>
      </tr>
  <% end %>
</table>

  <%= will_paginate @stats_all_time %>


</div>